"""Añadir tabla de roles

Revision ID: 151a4292fc0c
Revises: 26bac1276868
Create Date: 2023-11-24 07:38:20.880858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151a4292fc0c'
down_revision = '26bac1276868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    # ### end Alembic commands ###
